name: ISCG7444CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t flask-cicd-demo .

      - name: Run tests inside Docker container
        run: docker run --rm flask-cicd-demo pytest

      - name: Run application container
        run: |
          docker run -d -p 5000:5000 --name flask-test flask-cicd-demo
          sleep 5
          curl http://localhost:5000/health

      - name: Stop container
        run: docker stop flask-test
